# Generated by Django 4.2.4 on 2023-08-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.EmailField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('creation_date', models.DateField(max_length=70)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.user')),
            ],
        ),
    ]
