# Generated by Django 4.2.4 on 2023-08-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
